### ISSUE TITLE
Check for `int | float`

### ISSUE THREAD

**Issue by srittau** [PyCQA/flake8-pyi#221]
As `float` is a subtype of `int` (for type checking purposes), `int` is redundant. There might be other constellations that are worth checking.

**Comment by AlexWaygood** [comment]
For numeric types, the following are redundant (according to PEP 484):

- `float | int` (`int` is an implicit subtype of `float`)
- `complex | float` (`float` is an implicit subtype of `complex`)
- `complex | int` (`int` is an implicit subtype of `complex`)

**Comment by Zeckie** [comment]
But at runtime, they aren't subtypes (eg. using `type`, `isinstance` or `mro`), and they have some differences that would not be allowed if they were subtypes.

eg. `float` has `is_integer()` but `int` does not

https://github.com/python/mypy/issues/11511#issuecomment-965064459

**Comment by hauntsaninja** [comment]
Yes, that is true. But all static type checkers treat them this way and PEP 484 isn't going to change on this point. If anything, this makes even more of a case for linting here, since it alerts users to a mismatch between their expectations of how int float subtyping works and the reality of PEP 484.
