### ISSUE TITLE
Allow tuple default values?

### ISSUE THREAD

**Issue by AlexWaygood** [PyCQA/flake8-pyi#357]
I'd like to allow tuples as default values. Tuples are reasonably common as default values -- the empty tuple, in particular, is very common. I also don't see a particularly strong reason to disallow them. Tuples are immutable (as long as all their members are) and can be passed to `ast.literal_eval` (as long as all their members can be).

There's various kinds of objects I definitely _wouldn't_ want us to allow in default values (mutable objects; objects with long/complicated reprs; anything that can't be passed to `ast.literal_eval` outside of a few special-cased constants). But outside of those strictures, I also think it's in our interests to be as expansive as possible in the kinds of defaults we allow. We've seen over at typeshed that adding defaults to stubs can expose latent bugs in the stubs, and it's obviously helpful for users of IDEs as well.

Here are some proposed rules: we allow tuples iff:
- the tuple has <=5 elements in it
- the repr of the tuple is <=50 characters long
- every element of the tuple passes the rules we already have set out in this function:
  https://github.com/PyCQA/flake8-pyi/blob/f6118974eed9a2feea170d7634c32b1eaa138316/pyi.py#L722

Thoughts?

**Comment by JelleZijlstra** [comment]
I agree tuple defaults can be useful and should be allowed.

As for the restrictions, definitely agree that the elements should only be simple values that we'd otherwise allow as annotations. The way to think about these restrictions is that we should disallow defaults that are likely to be buggy, e.g. system-dependent defaults. For example, if something uses `tuple(sys.path)` as a default, we want to make sure we don't put that in a stub. I think a restriction on the number of tuple elements is a good proxy for that. I don't think we need your suggested restriction on the total repr(), since we'll already restrict the strings and ints within the tuple to reasonable values.

**Comment by srittau** [comment]
Personally, I would only restrict tuples to:

* Must be a tuple literal (no `tuple(sys.path)`).
* Elements must recursively pass the default check.

I.e. no length restriction. But I'm fine either way.

Slightly off-topic: Some more things I would allow: empty list, dict, and set literals. (Ok, there is no set literal, so I would allow `set()`.) I'm aware that these are potentially dangerous, but they are used in the wild. (I personally use them occassionally. And just to get more off-topic: I wish there was a __future__ import that would make default "safe".)

**Comment by AlexWaygood** [comment]
> Slightly off-topic: Some more things I would allow: empty list, dict, and set literals. (Ok, there is no set literal, so I would allow `set()`.) I'm aware that these are potentially dangerous, but they are used in the wild. (I personally use them occassionally. And just to get more off-topic: I wish there was a **future** import that would make default "safe".)

Very reluctant to allow `set()`, because that's a call expression, and it's nice for consistency if we don't allow any call expressions. I'd be happy to break that rule if it were a common default value, but I also don't think it's very common to have `set()` as a default. Open to all the others.
