### ISSUE TITLE
Add support for PEP742 rule

### ISSUE THREAD

**Issue by Skylion007** [PyCQA/flake8-pyi#496]
In [PEP 742](https://peps.python.org/pep-0742/), a new TypeIs annotation has been added. This provides an alternative to TypeGuard , which supports proper type narrowing. In vast majority of cases, people should use TypeIs as opposed to TypeGuard and the use of TypeGuard in code is likely a mistake.

It would therefore be nice to have a rule that bans the use of TypeGuard completely, just like the ANN401 rule, that bans typing.Any.

from: https://github.com/astral-sh/ruff/issues/12277

**Comment by AlexWaygood** [comment]
I think this would probably have too many false positives for a flake8-pyi rule. While it's true that `TypeIs` has the more intuitive behaviour and you should probably use it whenever it's safe to do so, it's not safe to do so 100% of the time. There are still a reasonable number of situations where you'll need to use `TypeGuard` to accurately describe a function, and I don't think it would be possible for us to statically distinguish the functions that should use `TypeIs` from the ones that are correctly using `TypeGuard` instead of `TypeIs`.

**Comment by JelleZijlstra** [comment]
Agree, TypeGuard is sometimes the right tool to use and flake8-pyi can't tell whether it is correct or not.

If you want to look for usages of TypeGuard, it's also really easy to do without a linter (just grep for the name TypeGuard), so a lint check wouldn't add that much value here.
